version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    entrypoint: ["sleep", "infinity"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
      - ./documentos/available_ingredients.csv:/data/available_ingredients.csv
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cocina_db


  fastapi_app:
    build:
      context: ./fastapi_app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
      - ./documentos:/app/documentos
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGO_DATABASE=cocina_db
      - OPENAI_API_BASE=https://api.openai.com/v1 
      - MODEL_NAME=gpt-4-turbo-preview
      - OPENAI_API_KEY=YOUR_OPENAI_API_KEY

volumes:
  mongodb_data: